version: '3'

services:
  gcc-cpp-sample:
    image: 'gcc:12.2'
    container_name: render

    volumes:
      - ../src/:/app/src
      - ../test/:/app/test
      - ../header/:/app/header/
      - ../image/:/app/image/
    working_dir: /app/src

    tty: true
